title: Ramprakash Baskar # your name (or website title) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Embedded Software Engineer currently working in Tesla. I graduated with a Masters degree in Electrical and Computer Engineering with specilisation in Embedded Systems from Portland State University  <br><br>
  The portfolio contains a list of Embedded Systems projects I worked as a Graduate Student.
  <br><br>
  <a href="www.linkedin.com/in/ramprakashbaskar">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
